sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t sherifahmed/frontend .

script :
  - docker run sherifahmed/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-003799728524"
  bucket_path: "dockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"